---
title: "About myself"
---
# About myself  
# Acerca de mi     
  
&nbsp;  
&nbsp;
      

I am currently working as a Postdoc Researcher in [Mueller's lab](https://www.plantpath.iastate.edu/people/daren-mueller) focusing in fungicide resistance and resistance management of the main foliar fungal diseases on soybean and corn in IA / Actualmente estoy trabajando como investigador postdoctoral Mueller's lab enfocado en resistencia a fungicidas de las principales enfermedades foliares fungosas de la soya y maiz en IA, [ISU](https://www.plantpath.iastate.edu/people). My boss leads the [Crop Protection Network](https://cropprotectionnetwork.org/peoples)

I am Ph Doctor in Plant Pathology (2016-2021) from / Soy doctor en Fitopatología de (2016-2021)[UNL](https://plantpathology.unl.edu)
 
My advisor was/ Mi consejera fue [Sydney Everhart](https://plantpathology.unl.edu/sydney-everhart)


My thesis was funded by/ Mi tesis fue financiada por [The North Central Soybean Research Program](http://www.ncsrp.com)  

Our collaborators were/ Nuestros colaboradores fueron:  
1. [Tamra Jackson (UNL)](https://cropwatch.unl.edu/author/tamra-jackson-ziems-extension-plant-pathologist)  
2. [Loren Giesler (UNL)](https://plantpathology.unl.edu/loren-giesler)  
3. [Daren Mueller (ISU)](https://www.plantpath.iastate.edu/people/daren-mueller)  
4. [Damon Smith (UW-Madison)](https://plantpath.wisc.edu/damon-smith-2/)  
5. [Martin Chilvers (MSU)](https://www.canr.msu.edu/people/chilvers_martin)  

My scholarhip was from Mexican government/ Mi beca fue financiada por el gobierno mexicano  [CONACyT](https://www.conacyt.gob.mx)


I am passionate about plant fungal pathogens. With huge tools of bioinformatics, I am fascinated about molecular genetic tools and scopes in order to get a finding that contributes to food safety for above 7 billion people where plant diseases is a great challenge/ Soy un apasionado de los hongos fitopatógenos. Con tanta diversidad en la bioinformática, me encuentro fascinado con la herramientas de genética molecular disponibles, enfocado a obtener conocimiento que contribuya con la seguridad alimentaria de poco más de 7 billones de personas, dónde las enfermedades fitopatógenas juegan un papel limitante   

I’m fond of Data Science. R, phyton, markdown and SQL enthusiast. Latex on basic skills/Soy un emprendedor de la ciencia de manejo de datos, R, phyton, markdown y SQL. Latex a nivel basico

Active reviewer of Plant Disease Journal and Mexican Journal of Phytopathology

