---
title: "LifeBlog"
---


# I hope you all are well!

My first post here in my _Life Blog_, I will talk briefly about one of my latest read books .

First one, I had the opportunity to revive what the colonel was experienced step by step until gets completely run out of money to buy something to eat, in the novel "**El coronel no tiene quien le escriba**" from the original text or "**No One Writes to the Colonel**" from the amazing writer _**Gabriel  García  Márquez**_.

 Two lessons gave me this book, first, how non-knowledgeable people can be and second how stubborn people can happen, even getting close the death. Many things came to mind meanwhile I was reading this book along with the person who most I love (my mom).

 The second book, "**La Tregua/The truce**" from the Uruguayan _**Mario Benedetti**_. Basically, _the diary of Martin Salomé_ taught me two main things. How hugely different we see things or events during all our life. And perhaps, the most important, to live in the present because we cannot assume anything for the upcoming future, wait, does it really exist?

I'll talk soon about these books: **Is that Fish on your Tomato? / Men Explain Things to Me** "mansplaining", **Lab Girl**, **The Solitude Labyrinth**, **Great Plains Bison**, and **The Stranger**.

