---
title: "Talks and Papers "
---

# Talks and Papers 
# Pláticas y Artículos
  
  
***corresponding author**    

R. Higgins, C. Wulkop, **E. H. Nieto-Lopez** and S. E. Everhart. 2020. Sources of white mold resistance derived from wide crosses in common bean and fungicide sensitivity of _Sclerotinia sclerotiorum_ from multi-site locations. Poster at Annual National Sclerotinia Initiative meeting in Fargo, ND.

Wulkop Gil C. A., E. H. Nieto-Lopez, S. E. Everhart. 2020. Fungicide Sensitivity of _Sclerotinia sclerotiorum_ isolates selected from five different states that use different fungicide treatments. Poster presentation, UCARE Research Fair, Spring 2020, UNL.

**Nieto-Lopez, E. H.**, T. J. J. Miorini, & S. E. Everhart 2019. Fungicide sensitivity of 207 _Sclerotinia sclerotiorum_ isolates from dry bean and soybean in the U.S. Poster presentation at the National Sclerotinia Initiative meeting in Fargo, ND.

**Nieto-Lopez, E. H.**, T. J. J. Miorini, & S. E. Everhart 2019. Fungicide sensitivity of 395 _Sclerotinia sclerotiorum_ isolates from dry bean and soybean. Poster presentation at APS Plant Health meeting, Cleveland, OH.

**Nieto-Lopez, E. H.**, T. J. J. Miorini, & S. E. Everhart 2019. Fungicide sensitivity of 207 _Sclerotinia sclerotiorum_ isolates from dry bean and soybean in the U.S. Poster presentation at UNL Spring Research Days, Lincoln, NE.

**Nieto-Lopez E. H.**, Everhart S. E. 2018.  Fungicide sensitivity and population structure of _Sclerotinia sclerotiorum_ from soybean in the north central United States and dry bean in Mexico. Student Seminar Series, Department of Agronomy & Horticulture, Lincoln, NE.

**Nieto-Lopez E. H.**, Miorini, T. J.,and Everhart S. E. 2018. Fungicide sensitivity of 42 _Sclerotinia sclerotiorum_ isolates in the North Central U.S. and determination of discriminatory concentrations. Oral presentation at North Central APS meeting 2018 in Fargo, ND. CONFERENCE PHYTOPATHOLOGY 108 (12), 33–33.

**Nieto-Lopez E. H.**, and Everhart S. E. 2017. Fungicide Sensitivity Population Structure of _Sclerotinia sclerotiorum_ from Soybean in the North
Central United States and Dry Bean in Mexico. Seminar at Department of
Plant Pathology, UNL

**Nieto-Lopez E. H.**, Miorini, T. J. J., Panullo, A., Steadman, J. R., and Everhart S. E. 2017. Fungicide sensitivity of _Sclerotinia sclerotiorum_ in the North Central United States. Poster at APS Annual Meeting  in Urbana-Champaign, IL. CONFERENCE PHYTOPATHOLOGY 107 (12), 175–175.

**Nieto-Lopez E. H.**, Miorini, T. J. J., Panullo, A., Steadman, J. R., and
Everhart S.E. 2017. Fungicide sensitivity of _Sclerotinia sclerotiorum_ in the
North Central United States. Poster at Poster at UNL Spring Graduate Research Fair 2017.

**Nieto-Lopez, E. H.**, Miorini, T. J. J., and Everhart, S. E. 2019. Fungicide sensitivity of 207 Sclerotinia sclerotiorum isolates from dry bean and soybean.2019. Annual Report of the Bean Improvement Cooperative 62: 22. USDA-ARS 24106 No. Bunn Road. http://www.bic.uprm.edu/?page_id=77

Velasco-Hernandez, A., Saucedo-Veloz, C., Nieto-Angel, R., Ramirez-Guzman, M. E., Saucedo-Veloz, D., and **Nieto-Lopez, E. H**. 2017. Fruit growth, maturation, and shelf life of two cultivars of tejocote _Crataegus mexicana_ Moc. & Sessé. Fruits 04/2017; 72(2)., DOI:
http://www.pubhort.org/fruits/72/2/2/index.htm

Nieto-Angel, R., Hernandez-Pigmeo, F., Tovar-Pedraza, J. M., Betancourt-Olvera, M., Manuel-Pinto, V., Leyva-Mir, S. G., Alonso-Henandez, L., Muniz-Merino, M., Muniz-Reyes E., Santiago-Felipe, M., and **Nieto-Lopez, E. H***. 2016. Evaluation of Traps and Attractants to Monitor _Rhagoletis pomonella_ in Tejocote _Crataegus mexicana_ in Mexico. Southwestern Entomologist 06/2016; 41(2):561-566., DOI:
http://www.bioone.org/doi/10.3958/059.041.0224

Nunez-Colin, C. A., Nieto-Angel, R., Barrientos-Priego, A. F., and **Nieto-Lopez, E. H.** Cultivar Descriptions of Tejocote. 2016. HortScience: a publication of the American Society for Horticultural Science 06/2016; Register
of New Fruit and Nut Cultivars List 48(56:6):649. DOI:
http://hortsci.ashspublications.org/content/51/6/620.full.pdf+html


