---
title: "Projects"
---
  

# Proyectos

1. [Fungicide sensitivity monitoring for fungi affecting the main crops for Mexico/Monitoreo de la sensibilidad a fungicidas de los hongos que afectan los principales cultivos de México](https://www.researchgate.net/project/Fungicide-sensitivity-monitoring-for-fungi-affecting-the-main-crops-for-Mexico)  

2. [Identification of plant pathogenic fungi and oomycetes in Mexico/Identificación de hongos fitopatógenos y oomicetos de México](https://www.researchgate.net/project/Identification-of-plant-pathogenic-fungi-and-oomycetes-in-Mexico)



My collaborators are Alma Rosa Solano-Báez from UPAEP, Elizabeth García-León from INIFAP, Santos Gerardo Leyva-Mir and Moises Camacho-Tapia from UACh and Juan Manuel Tovar-Pedraza from CIAD/ Mis colaboradores son [Alma Rosa Solano-Báez]( https://www.researchgate.net/lab/Alma-Rosa-Solano-Baez-Lab-2) de la [UPAEP](https://www.upaep.mx), [Elizabeth García-León](https://www.researchgate.net/profile/Elizabeth_Garcia-Leon?_iepl%5BviewId%5D=rOtg2QiDnakel5oPwxKBBfDN&_iepl%5Bcontexts%5D%5B0%5D=projectUpdatesLog&_iepl%5BinteractionType%5D=projectViewCollaboratorProfile) del [INIFAP](https://www.gob.mx/inifap), [Santos Gerardo Leyva-Mir](https://www.researchgate.net/profile/Santos_Leyva-Mir) y [Moises Camacho-Tapia](https://www.researchgate.net/profile/Moises_Camacho-Tapia2) de la [Universidad Autónoma Chapingo](http://web.chapingo.mx), y  [Juan Manuel Tovar-Pedraza](https://www.researchgate.net/profile/Juan_Tovar-Pedraza) del [Centro de Investigación en Alimentación y Desarrollo](https://www.ciad.mx)

