---
title: "Research"
---
  

# Investigación

My currently research is focused on the identification of Cercospora spp. involved in Cercospora leaf blight and purple seed stain on soybean previously known to be caused by a solo species, _C. kikuchii_. Once the species identification is done, I will characterize them for fungicide resistance mainly for QoIs and DMIs. Here, Iam currently preparing a paper about the species and the fungicide sensitivity found in IA; interesting results so far. 

I am also investigating the incidence of Brown spot _Septoria glycines_ under different management practices. Here I have gotten zero results since not conducive conditions.  Iam developing a project with Msc. [Parbati Joshi](https://www.ppem.iastate.edu/people/parbati-joshi) an contribution of PhD student [Daniel Cerritos](https://psla.uconn.edu/person/daniel-garcia/).



Also, part of the job, we are running many plot trials of fungicide efficacy for the main fungal diseases of soybean and maize. I am along with [Dr. Nabin Kumar Dangal](https://www.researchgate.net/profile/Nabin-Dangal-2) responsible of the data collection and analyses of these trials and PhD student [Jose Gonzalez](https://www.ppem.iastate.edu/people/jose-gonzalez-acuna). Also MSc [Stith Wiggs](https://www.plantpath.iastate.edu/people/stith-wiggs) is in charged of all field activities as planting, irrigation system, fungicide sprays, crop management and all related with the plot research and the experimental design. Likewise Jose is in charged of all logistis and is the lab manager.

Graduate students and postdocs require highly demanding hourly help to get done many of their projects. The past and ongoing projects have been greatly helped by [Emma Alstott](https://www.news.iastate.edu/news/2024/04/16/2024goldwater), [Alex Bray](https://www.linkedin.com/in/alex-bray-4a7619228/), [Daniel Gill](https://www.ndsu.edu/agriculture/academics/academic-units/plant-pathology/our-people/graduate-students), [Kaylee Olgren](https://www.linkedin.com/in/kaylee-olgren-b4514a223/), [Anna Schacher](https://www.linkedin.com/in/anna-schacher-b9a4941b7/?trk=public_profile_browsemap_profile-result-card_result-card_full-click), [Sarah Fleming](https://www.linkedin.com/in/sarah-fleming-b2285b304/), and [Savannah Tiffany](https://www.linkedin.com/in/savannah-tiffany-3074531a1/). 

My main Mexican collaborators are  [Dr. Diego Jarquin](https://agronomy.ifas.ufl.edu/people/diego-jarquin/) and [Dr. Juan Manuel Tovar-Pedraza](https://www.researchgate.net/profile/Juan-Tovar-Pedraza).

My doctoral research was focus on the study of risk of fungicide resistance emergence in [_Sclerotinia sclerotiorum_](https://onlinelibrary.wiley.com/doi/full/10.1111/j.1364-3703.2005.00316.x)
known as white mold, a fungal pathogen that causes disease outbreaks on soybean. Keen, the aims are  to determine fungicide sensitivity of populations from soybean; evaluate the effect of different fungicide applications on the sensitivity of field populations; and characterize the population structure and genetic diversity populations from soybean throughout the North Central United States and Mexico./ Mi  investigación doctoral estuvo enfocada en el estudio del riesgo a la emergencia de la resistencia a fungicidas por [_Sclerotinia sclerotiorum_](https://onlinelibrary.wiley.com/doi/full/10.1111/j.1364-3703.2005.00316.x)  conocido como moho blanco, un hongo fitopatógeno que causa enfermedad en soya. Los objetivos son, determinar la sensibilidad a fungicidas de poblaciones de soya; evaluar el efecto de diferentes aplicaciones de fungicidas en la sensibilidad de la poblaciones directamente en el campo; y caracterizar la estructura poblacional y diversidad genética de poblaciones de soya dentro Estados Unidos central y México  

My thesis title was "Fungicide Sensitivity and Population Structure of _Sclerotinia sclerotiorum_ from Soybean in
the North Central United States and Dry Bean
in Mexico"/ El título de mi tesis fue  "Sensibilidad a fungicidas y estructura poblacional de _Sclerotinia sclerotiorum_ de soya en Estados Unidos central y de fríjol en México".